### ISSUE TITLE
Flickity Swipe Function with Wordpress 

### ISSUE THREAD

**Issue by ghost** [RadGH/WooCommerce-Flickity-Gallery#1]
First at all: Great Plugin! :+1: Nice work! Keep going! :)
But the Flickity swipe function is not working with wp 4.5.3.. Any ideas?
Best

**Comment by RadGH** [comment]
Hey, thanks for using the plugin!

I actually didn't use the swipe feature for the main photo because the lightbox would open if you dragged a photo sometimes. I did some more research and found Flickity does provide a "staticClick" event which only fires if you did not drag a slide. I'll have to trigger the lightbox manually on that event.

I'll have an update for that soon.

Thanks :)

**Comment by RadGH** [comment]
This new feature has been added. It includes the latest version of Flickity. Nothing should break unless you are using flickity elsewhere, but in most cases everything should continue to work even if that is the case.

Thanks again for the feedback. Sorry it took so long.
